[window]
opacity = 0.9
[general]
import = [
    "~/.config/alacritty/themes/themes/iterm.toml"
]

[font]
size = 11.0

[font.bold]
style = "Bold"
family = "JetBrainsMono Nerd Font Mono"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
style = "Regular"
family = "JetBrainsMono Nerd Font Mono"
